### ISSUE TITLE
Why lxml dependency?

### ISSUE THREAD

**Issue by Diaoul** [pbs/pycaption#114]
I've searched the code for lxml but couldn't find any result. Do you use it?

lxml is a strong requirement as it's not a pure python and even if it makes parsing faster with beautifulsoup I think it should be an optional (extras) requirement.

**Comment by vladiibine** [comment]
We had troubles with the other parsers, and found this one to be the most non-buggy. 
I'm talking things like, the parser would automatically add a <html></html> tag surrounding everything,  not escaping some tags properly. Eliminating this dependency would take quite a bit of work in the DFXP parser. But I guess since some people might not care about dfxp, then It's a good idea to eliminate the dependency, at least for those people.

**Comment by arielpontes** [comment]
The library is not explicitly called in our source code, but it's call by bs4 every time we instantiate a `BeautifulSoup` object passing the string "xml" as a parser (see more [here](http://www.crummy.com/software/BeautifulSoup/bs4/doc/#installing-a-parser)). If you `pip uninstall lxml` and run the test suite you can see in more detail where pycaption breaks.
