### ISSUE TITLE
Invalid characters in WebVTT Text

### ISSUE THREAD

**Issue by webnard** [pbs/pycaption#48]
According to the [WebVTT specification](http://dev.w3.org/html5/webvtt/#dfn-webvtt-cue-text-span), "A WebVTT cue text span consists of one or more characters other than U+000A LINE FEED (LF) characters, U+000D CARRIAGE RETURN (CR) characters, U+0026 AMPERSAND characters (&), and U+003C LESS-THAN SIGN characters (<)."

Am I incorrect in understanding that unless the span in question is one of a very limited set of elements (class, italics, bold, underline, ruby, voice, language, or timestamp[¹](http://dev.w3.org/html5/webvtt/#h4_webvtt-cue-text)), characters such as `<` and `>` should be escaped to `&lt;` and `&gt;`, respectively? The WebVTT sample used in testing currently [does not have these escaped](https://github.com/pbs/pycaption/blob/ace6b4ae8e6753b28328cb18981c3992fac2681e/tests/samples.py#L392), and the [JavaScript WebVTT parser](https://quuz.org/webvtt/) throws an [error](https://github.com/annevk/webvtt/blob/2202335bc6138ad27d0d7fd0f61f17598e515b49/parser.js#L479) when the `<` character is used like this.

**Comment by arielpontes** [comment]
Fixed in 6586819659. There is still a sample with the illegal `<` character, but we chose to keep it there to ensure that, although the WebVTTWriter never outputs it, the WebVTTReader can still read it without failing. We allow it on read because many players also do (e.g. Chrome, Firefox and Safari) even though according to the specification it is indeed not allowed.
