### ISSUE TITLE
Unicode objects in __all__ dictionary should be replaced with strings.

### ISSUE THREAD

**Issue by vladiibine** [pbs/pycaption#53]
As demonstrated by PR #52 list members in the __all__ module attribute should be strings, not unicode objects.

**Comment by vladiibine** [comment]
pycaption was not abandoned, but its maintenance is not high up on the priority list

**Comment by dwbuiten** [comment]
I would say sitting *completely broken* for months, with other important PRs like 6 months with 0 response, is pretty much dead.

I've had to use a fork for almost a year now, because mainline won't pull our changes (or respond even), so I'm thinking I'll have to write my own lib, or just merge mainline into our fork when it gets its annual push (which may or may not break it because it wasn't tested).

**Comment by vladiibine** [comment]
Merged. Closing the issue
