### ISSUE TITLE
Several tests seem to test python's native str.decode method rather than pycaption

### ISSUE THREAD

**Issue by arielpontes** [pbs/pycaption#84]
All caption formats seem to have 3 tests that do exactly the same thing with the difference that the samples it uses are in some cases bytestrings (utf8 encoded) and in others unicode strings . In any case the content is the same and, most importantly, the input that is finally sent to the reader is already converted to unicode. This seems pretty redundant and the tests can probably be safely removed.

**Comment by vladiibine** [comment]
Historically, there was a time when PyCaption didn't handle text (unicode that is) well enough. I think the purpose of these tests could to simply ensure undecoded bytes can't be fed into pycaption. So there is value in ensuring that all the readers throw an exception if undecoded bytes are used for input. There is less value, I think, in ensuring that the output is text (unicode for Python2.X), because we can't really do this in a unit-testable way, for all possible scenarios.

For the readers, I think the unit tests can remain, though they should be moved to a separate, more semantically named module.

For the writers we could use the `__future__` import `unicode_literals`.
The module guarantees the "No feature will ever be removed from the module" so that makes pycaption future proof, and guarantees that we can't really write bytes, except intentionally, by encoding the literals

**Comment by arielpontes** [comment]
If the purpose of these tests is, as you say, to "_ensure undecoded bytes can't be fed into pycaption_", then they are wrong because they **_do not_** ensure this. I disagree, therefore, that any of these tests should reamin. What I do agree with is that there would be value in a including tests that do ensure this in a future fix.

I checked the commit history and found that indeed, historically the tests made sense. Pycaption supported both unicode and bytestring at one point, so it made sense to add **_different_** inputs such as samples with special characters represented both as utf-8 encoded bytestrings and unicode strings. However, after commit f163ff0, all readers were changed to only support unicode, and instead of removing tests that became redundant, utf-8 bytestrings were simply decoded to unicode before being passed to the reader. This means all utf8 tests cover **exactly** the same code as the unicode tests. Besides, the older tests which tested samples without special characters can also be removed because they as well are redundant. There is no need to test a conversion with pure ascii text **and** with special characters. Testing only samples with special characters is sufficient.
